//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int IdFactura { get; set; }
        public int IdArticulo { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
